service: aws-node-loadserve

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}
  environment:
    STAGE: ${self:provider.stage}
    tableContacts: ${self:custom.contactsTable}
    tableLedger: ${self:custom.ledgerTable}
    tableAccount: ${self:custom.accountTable}
  apiGateway:
    request:
      schemas:
        create-contact-model:
          name: CreateContactModel
          schema: ${file(schema/create_contact.json)}
          description: "A Model validation for creating contact"
        add-wallet-model:
          name: AddWalletModel
          schema: ${file(schema/add_wallet.json)}
          description: "A Model validation for adding credits to wallet"
        add-load-credit-model:
          name: AddLoadCreditModel
          schema: ${file(schema/add_loadcredit.json)}
          description: "A Model validation for adding load credit"
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

custom:
  stages:
    - local
    - dev
    - prod
  contactsTable: Contacts
  ledgerTable: Ledger
  accountTable: Account
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8097
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  webpack:
    webpackConfig: ./webpack.config.js 
    includeModules: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
  createContact:
    handler: src/contacts.create
    events:
      - http:
          path: /contact
          method: post
          request:
            schemas:
              application/json: create-contact-model
  addLoadWallet:
    handler: src/wallet.create
    events:
      - http:
          path: /wallet
          method: post
          request:
            schemas:
              application/json: add-wallet-model
  addLoadCredit:
    handler: src/loadcredit.create
    events:
      - http:
          path: /load
          method: post
          request:
            schemas:
              application/json: add-load-credit-model

resources:
  Resources:
    Contacts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.contactsTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    Ledger:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ledgerTable}
        AttributeDefinitions:
          - AttributeName: DateTransact
            AttributeType: S
          - AttributeName: ContactID
            AttributeType: S
        KeySchema:
          - AttributeName: DateTransact
            KeyType: HASH
          - AttributeName: ContactID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    Account:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accountTable}
        AttributeDefinitions:
          - AttributeName: DateTransact
            AttributeType: S
          - AttributeName: ContactID
            AttributeType: S
        KeySchema:
          - AttributeName: DateTransact
            KeyType: HASH
          - AttributeName: ContactID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2