service: aws-node-loadserve

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}
  environment:
    STAGE: ${self:provider.stage}
    tableContacts: ${self:custom.contactsTable}
    tableLedger: ${self:custom.ledgerTable}
    tableRetail: ${self:custom.retailTable}
    tableAccount: ${self:custom.accountTable}
    dynamodbPort: ${self:custom.dynamodb.start.port}
  apiGateway:
    request:
      schemas:
        create-contact-model:
          name: CreateContactModel
          schema: ${file(schema/create_contact.json)}
          description: "A Model validation for creating contact"
        add-wallet-model:
          name: AddWalletModel
          schema: ${file(schema/add_wallet.json)}
          description: "A Model validation for adding credits to wallet"
        add-load-credit-model:
          name: AddLoadCreditModel
          schema: ${file(schema/add_loadcredit.json)}
          description: "A Model validation for adding load credit"
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

custom:
  stages:
    - local
    - dev
    - prod
  contactsTable: Contacts
  ledgerTable: Ledger
  retailTable: Retail
  accountTable: Account
  dynamodb:
    stages:
      - local
    start:
      port: 8097
      dbPath: ./db
      migrate: true
    migration:
      dir: offline/migrations
  webpack:
    webpackConfig: ./webpack.config.js 
    includeModules: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
  createContact:
    handler: src/contacts.create
    events:
      - http:
          path: /contact
          method: post
          request:
            schemas:
              application/json: create-contact-model
  listContact:
    handler: src/contacts.list
    events:
      - http:
          path: /contacts
          method: get
  deleteContact:
    handler: src/contacts.remove
    events:
      - http:
          path: /contact/{ID}
          method: delete
  consumerLoad:
    handler: src/consumer.load
    events:
      - http:
          path: /consumer/load
          method: post
          request:
            schemas:
              application/json: add-wallet-model
  addLoadCredit:
    handler: src/loadcredit.create
    events:
      - http:
          path: /load
          method: post
          request:
            schemas:
              application/json: add-load-credit-model
  listLoadCredit:
    handler: src/loadcredit.list
    events:
      - http:
          path: /loads
          method: get

resources:
  Resources:
    Contacts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.contactsTable}
        AttributeDefinitions:
          - AttributeName: ContactID
            AttributeType: S
        KeySchema:
          - AttributeName: ContactID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
    Ledger:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ledgerTable}
        AttributeDefinitions:
          - AttributeName: ContactID
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: N
          - AttributeName: ActivityType
            AttributeType: S
        KeySchema:
          - AttributeName: ContactID
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        LocalSecondaryIndexes:
        - IndexName: ContactActivity
          KeySchema:
          - AttributeName: ContactID
            KeyType: HASH
          - AttributeName: ActivityType
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
    LoadRetail:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.retailTable}
        AttributeDefinitions:
          - AttributeName: ActivityType
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: ActivityType
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        LocalSecondaryIndexes:
        - IndexName: ContactActivity
          KeySchema:
          - AttributeName: ContactID
            KeyType: HASH
          - AttributeName: ActivityType
            KeyType: RANGE
          Projection:
            ProjectionType: ALL